### ISSUE TITLE
Fractional Usage Q4 TODO

### ISSUE THREAD

**Issue by jordajm** [OriginProtocol/origin#1108]
**General Bugs/Tasks**
- [x] Get “my purchases” and “my sales” working for fractional listings
- [x] Fix start/end dates in buyer's offer slots - currently they're just copies of the start/end dates of the event that the seller created, which may span multiple slots
- [x] replace slot.recurs with slot.rrule and use that to define repeating logic
- [ ] How can we allow sellers to select hourly/daily and slot time length?
- [x] Listing detail - make sure buyer is not also seller - hide “reserve” button if so
- [x] How should we handle daylight savings time in relation to slot start/end dates so they don’t become an hour off when the time changes?
- [ ] How do we want to handle past dates being disabled when it’s late in the week and the whole calendar is disabled
- [x] as a seller, viewing offers page (/purchases/<listingId>) throws an error
- [x] See if seller/buyer steps make sense for fractional
- [x] localization of calendar strings
- [x] Hourly calendar (maybe edit mode) - for newly created events, can’t create event that includes the slot right after an existing event
- [x] Hourly calendar  (maybe edit mode) - for newly created events, can’t create an overriding non-repeating event
- [x] Hourly calendar - in edit mode, event end times show one minute before the desired end time
- [x] Why do new events sometimes default to unavailable?
- [x] /update/:listingId route should check to make sure user is listing’s seller before rendering for security purposes
- [x] Test edit listing and fix bugs
- [x] buyer’s calendar - style “unavailable” message to look more like error message

**Create listing flow**
- [x] clicking “back” without interacting with calendar doesn’t fire the “onGoBack” callback
- [x] Step number, step title, description, etc are missing from “AVAILABILITY” step
- [ ] If you go back and change the category of the listing from unit to fractional (and maybe other cases), form validation fails in details step

**Styling**
- [x] Make seller's calendar look like Aure's design (get rid of horizontal event bars, etc)
- [x] Use the gray background that we use for “in the past” instead of slashes to represent unavailable slots 
- [x] On seller’s calendar, past dates should show gray background
- [ ] (Stretch goal) mobile layout / styling for calendar component 
- [x] add hover state to calendar time slots to emphasize interactive features

**Schemas**
- [ ] create 2.0.0 dapp schemas for all fractional listing types
    - [ ] update listingSchemaMetadata
    - [ ] add an entry for mapping each deprecated 1.0.0 schema in schemaAdapter

**Comment by wanderingstan** [comment]
For discussion and reference, here's what the underlying json is looking like: 

Representation of available slots on a listing:
```
{  
  "dappSchemaId":"https://dapp.originprotocol.com/schemas/forRent-housing_1.0.0.json",
  "category":"schema.forRent",
  "subCategory":"schema.housing",
  "language":"en-US",
  "title":"A test house",
  "description":"a dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk daa dk da",
  "listingType":"fractional",
  "commission":{  
    "amount":"50",
    "currency":"OGN"
  },
  "unitsTotal":1,
  "slots":[  
    {  
      "startDate":"2018-12-03T07:00:00.000Z",
      "endDate":"2018-12-06T06:59:58.000Z",
      "isAvailable":true,
      "price":{  
        "currency":"ETH",
        "amount":"0"
      }
    },
    {  
      "startDate":"2018-12-31T07:00:00.000Z",
      "endDate":"2019-01-06T06:59:58.000Z",
      "isAvailable":true,
      "price":{  
        "currency":"ETH",
        "amount":"1"
      }
    },
    {  
      "startDate":"2018-12-24T07:00:00.000Z",
      "endDate":"2018-12-29T06:59:58.000Z",
      "isAvailable":true,
      "price":{  
        "currency":"ETH",
        "amount":"1"
      }
    },
    {  
      "startDate":"2019-01-06T07:00:00.000Z",
      "endDate":"2019-01-24T06:59:59.000Z",
      "isAvailable":true,
      "price":{  
        "currency":"ETH",
        "amount":"2"
      }
    }
  ],
  "slotLength":1,
  "slotLengthUnit":"schema.days",
  "media":[  

  ],
  "schemaId":"https://schema.originprotocol.com/listing_1.0.0.json"
}
```

Offer
```
{  
  "listingId":"999-000-5",
  "listingType":"fractional",
  "totalPrice":{  
    "amount":"4",
    "currency":"ETH"
  },
  "commission":{  
    "amount":"0",
    "currency":"OGN"
  },
  "finalizes":31536000,
  "slots":[  
    {  
      "startDate":"2018-12-25T07:00:00.000Z",
      "endDate":"2018-12-28T07:00:00.000Z",
      "price":{  
        "currency":"ETH",
        "amount":"1"
      }
    },
    {  
      "startDate":"2018-12-25T07:00:00.000Z",
      "endDate":"2018-12-28T07:00:00.000Z",
      "price":{  
        "currency":"ETH",
        "amount":"1"
      }
    },
    {  
      "startDate":"2018-12-25T07:00:00.000Z",
      "endDate":"2018-12-28T07:00:00.000Z",
      "price":{  
        "currency":"ETH",
        "amount":"1"
      }
    },
    {  
      "startDate":"2018-12-25T07:00:00.000Z",
      "endDate":"2018-12-28T07:00:00.000Z",
      "price":{  
        "currency":"ETH",
        "amount":"1"
      }
    }
  ],
  "schemaId":"https://schema.originprotocol.com/offer_1.0.0.json"
}
```

**Comment by joshfraser** [comment]
Thanks for flagging this @wanderingstan. Since this will effectively be the protocol for all calendar-based listings, we should be thoughtful about how we design this schema. I think we should be able to come up with a cleaner format for representing available time slots that is more concise, more human readable and easier to validate.

**Comment by wanderingstan** [comment]
Here is the latest json format for listing and offer:

## Listing
```json
{  
  "dappSchemaId":"https://dapp.originprotocol.com/schemas/forRent-housing_1.0.0.json",
  "category":"schema.forRent",
  "subCategory":"schema.housing",
  "language":"en-US",
  "title":"Stan's House",
  "description":"adf dfa ds adf dfa dsadf",
  "listingType":"fractional",
  "commission":{  
    "amount":"50",
    "currency":"OGN"
  },
  "unitsTotal":1,
  "slots":[  
    {  
      "startDate":"2018-12-01T07:00:00.000Z",
      "endDate":"2018-12-03T06:59:59.000Z",
      "isAvailable":true,
      "price":{  
        "currency":"ETH",
        "amount":"2"
      },
      "rrule":"FREQ=DAILY;"
    },
    {  
      "startDate":"2018-12-30T07:00:00.000Z",
      "endDate":"2019-01-06T06:59:59.000Z",
      "isAvailable":true,
      "price":{  
        "currency":"ETH",
        "amount":"3"
      }
    },
    {  
      "startDate":"2018-12-17T07:00:00.000Z",
      "endDate":"2018-12-22T06:59:59.000Z",
      "isAvailable":false,
      "price":{  
        "currency":"ETH",
        "amount":"0"
      }
    }
  ],
  "slotLength":1,
  "slotLengthUnit":"schema.days",
  "media":[  

  ],
  "schemaId":"https://schema.originprotocol.com/listing_1.0.0.json"
}
```

## Offer

```json
{
  "listingId":"999-000-5",
  "listingType":"fractional",
  "totalPrice":{
    "amount":"11.00000",
    "currency":"ETH"
  },
  "commission":{
    "amount":"0",
    "currency":"OGN"
  },
  "finalizes":31536000,
  "slots":[
    {
      "startDate":"2018-12-29T07:00:00.000Z",
      "endDate":"2018-12-30T06:59:59.000Z",
      "price":{
        "currency":"ETH",
        "amount":"2"
      },
      "rrule":"FREQ=DAILY;"
    },
    {
      "startDate":"2018-12-30T07:00:00.000Z",
      "endDate":"2018-12-31T06:59:59.000Z",
      "price":{
        "currency":"ETH",
        "amount":"3"
      }
    },
    {
      "startDate":"2018-12-31T07:00:00.000Z",
      "endDate":"2019-01-01T06:59:59.000Z",
      "price":{
        "currency":"ETH",
        "amount":"3"
      }
    },
    {
      "startDate":"2019-01-01T07:00:00.000Z",
      "endDate":"2019-01-02T06:59:59.000Z",
      "price":{
        "currency":"ETH",
        "amount":"3"
      }
    }
  ],
  "schemaId":"https://schema.originprotocol.com/offer_1.0.0.json"
}
```

**Comment by jordajm** [comment]
Closing b/c I created new issues to track the unfinished items in this issue
