### ISSUE TITLE
Deprecate origin-js

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#1752]
Here are the tasks that need to be completed before we can finally get rid of origin-js:
 - [ ] #1749 - Delete old Identity code
 - [x] #1746 - Remove @origin/mobile dependency on @origin/js
 - [x] #1750 - Remove discovery server dependency on origin-js
 - [x] #1751 - Remove listener dependency on origin-js
