### ISSUE TITLE
Marketplace Contract v01

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2007]
This tracks the various improvements that should be made to the next version of our marketplace smart contract.

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by nick** [comment]
- [ ] Add topic to addData
- [ ] Change 'listing' to 'seller'
- [ ] Allow seller address to be updated
