### ISSUE TITLE
Refined DApp Messaging

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/origin#2719]
This tracks a growing list of issues with our DApp messaging experience and visual elements.

-----

At Origin, we use [ZenHub](https://www.zenhub.com/) to manage our engineering tasks and product development. [Download their browser extension](https://www.zenhub.com/extension) and check out our open workspace at [github.com/originprotocol/origin#zenhub](https://github.com/originprotocol/origin#zenhub).

**Comment by micahalcorn** [comment]
**Sub-tasks**

- [ ] add separators between conversation list items as shown [here](https://zpl.io/bo8nmJX)
- [ ] keep send button visible at all times (at least for photo upload)
- [ ] auto-scroll to the latest message when the conversation is opened
- [ ] pin input field to bottom of the screen
