### ISSUE TITLE
August campaign blocking issues

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/origin#2809]
**Todo before prod push**
 - [x] Enable Twitter subscription in prod
 - [x] Run attestation backfill in prod
 - [x] Add all social content [per doc](https://docs.google.com/spreadsheets/d/1akbpgFFy5vW-PszmcJNImIW2rjkiwDk4xVXlUO7fMzo/edit#gid=1116035166) to prod rules 

**Known open issues:**

**Fixed, needs verification**
 - [x] Crash when clicking on Purchase page. Is that an issue with the featured listings ?
 - [x] On may campaign page, Purchases, Promote Origin, Follow Origin are unlocked even though I do not have any attestations. They should be locked. Only the Invitations action is locked correctly. 
 - [x] Sharing verfication. Problem with shortened URLs and invalid content hash. Seems like one of the tweets just has ogn.dev/mobile where as twitter returns https://ogn.dev/mobile (PR #2810)
 - [x] Identity.data.twitterProfile not populated. Fixed in https://github.com/OriginProtocol/origin/commit/70112a55c9c0ffa6e59d8c4a78af2bae2ed8a0a0 and deployed to staging.
- [x] 0 reward given for sharing Twitter content https://github.com/OriginProtocol/origin/pull/2843

**Josh's feedback:**
- [x] can we put the sharable articles in 2 columns on desktop?
- [x] need a space between "Follow" and "Origin" on the follow Origin page
- [x] the "Join @OriginProtocol on #Telegram!" tweet needs a link (https://t.me/originprotocol). DONE (Franck)
- [x] on the sharable articles, the Origin logo is huge and should be a rectangle instead of a square. we should use the full logo instead of the "O"

**Comment by franckc** [comment]
@shahthepro @sparrowDom I created this issue as a master list for keeping track of known blocking bugs for the August campaign launch. Can I get your help with investigating and fixing ? If you have fixes, please do feel free merge and deploy to staging. Do not wait for me... Thanks :)

**Comment by shahthepro** [comment]
Getting this GraphQL error after a successful verification. Debugging it
![Screenshot 2019-07-31 at 3 36 21 PM](https://user-images.githubusercontent.com/10547529/62203592-197d5580-b3a9-11e9-86e5-b3a8405cea12.png)

**Comment by franckc** [comment]
Some feedback from @joshfraser  while testing on staging:
1. can we put the sharable articles in 2 columns on desktop?
2. need a space between "Follow" and "Origin" on the follow Origin page
3. the "Join @OriginProtocol on #Telegram!" tweet needs a link (https://t.me/originprotocol)
4. on the sharable articles, the Origin logo is huge and should be a rectangle instead of a square. we should use the full logo instead of the "O"

**Comment by sparrowDom** [comment]
I get stuck on this page when trying to share an article

![Screenshot_20190801-170552](https://user-images.githubusercontent.com/579910/62304724-dbeafc00-b47e-11e9-9130-9c404ef218f7.jpg)

**Comment by shahthepro** [comment]
@sparrowDom Is that on Android?

**Comment by sparrowDom** [comment]
Yup Android

**Comment by franckc** [comment]
Everything is fixed so closing this issue. Now that we launched, let's open separate individual issue for any remaining bug.

**Comment by franckc** [comment]
Let me open a separate issue to track the Android bug... then will close this issue.

**Comment by franckc** [comment]
Opened https://github.com/OriginProtocol/origin/issues/2844 to track the Android bug. Closing this issue now.
